# =============================================
# Williams F1 Full AD Audit – Shared Account Discovery
# File: /scripts/williamsf1-ad-audit.ps1
# Author: Curtis-Davidson & Urbantek
# Version: 2025.6.4
# =============================================

# === IMPORTS ===
Import-Module ActiveDirectory -ErrorAction Stop
. "$PSScriptRoot\..\config\audit-config.ps1"
. "$PSScriptRoot\..\lib\core-functions.ps1"

Write-Host "`n[INFO] Starting Williams F1 Shared Account Full Audit..." -ForegroundColor Cyan

# === OUTPUT SETUP ===
if (!(Test-Path $OutDir)) {
    New-Item -ItemType Directory -Path $OutDir -Force | Out-Null
}

# === INIT REPORT HEADERS ===

# CSV
"Username,DisplayName,OU,LastLogon,Enabled,Groups,GPOs,ACLs,Exchange,DriveMaps" | Out-File $csvOut -Encoding UTF8

# Markdown
# Purpose: Clear visual structure for reviewing shared accounts by auditors
# Instruction: Replace Markdown block with the following template inside orchestrator
# Expected Result: Human-readable report grouped by user with clear flags

@"
# Williams F1 – Shared Account Intelligence Report
**Date:** $ts
**Generated By:** williamsf1-ad-audit.ps1
**Scope:** Full AD Tree User & Group Discovery

---

| Username | DisplayName | OU | Enabled | Last Logon | Group Count |
|----------|-------------|----|---------|------------|-------------|
"@ | Out-File $mdOut -Encoding UTF8

# HTML
# Purpose: Professional dark theme with high contrast, scrollable tables
# Instruction: Replace HTML header block inside orchestrator with below
# Expected Result: Clean modern UI, mobile-friendly, sortable via JavaScript (optional)

$htmlHeader = @"
<!DOCTYPE html>
<html lang='en'>
<head>
<meta charset='UTF-8'>
<title>Williams F1 Shared Account Audit</title>
<style>
  body        { font-family: 'Segoe UI', sans-serif; margin: 20px; background: #1e1e1e; color: #ccc; }
  h1          { color: #fff; }
  table       { width: 100%; border-collapse: collapse; margin-top: 12px; }
  th, td      { border: 1px solid #333; padding: 10px; text-align: left; }
  th          { background: #007acc; color: white; }
  tr:nth-child(even) { background-color: #2a2a2a; }
  tr:hover    { background-color: #444; }
</style>
</head>
<body>
<h1>Williams F1 – Shared Account Audit</h1>
<p><b>Generated:</b> $ts</p>
<script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>
<table id="auditTable">
<thead>
<tr>
<th onclick="sortTable(0)">Username</th>
<th onclick="sortTable(1)">Display Name</th>
<th onclick="sortTable(2)">OU</th>
<th onclick="sortTable(3)">Enabled</th>
<th onclick="sortTable(4)">Last Logon</th>
<th onclick="sortTable(5)">Group Count</th>
</tr>
</thead>
<tbody>
</tbody>
</table>
<script>
function sortTable(n) {
  var table, rows, switching, i, x, y, shouldSwitch, dir = "asc", switchcount = 0;
  table = document.getElementById("auditTable");
  switching = true;
  while (switching) {
    switching = false; rows = table.rows;
    for (i = 1; i < (rows.length - 1); i++) {
      shouldSwitch = false;
      x = rows[i].getElementsByTagName("TD")[n];
      y = rows[i + 1].getElementsByTagName("TD")[n];
      if ((dir == "asc" && x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) ||
          (dir == "desc" && x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase())) {
        shouldSwitch = true; break;
      }
    }
    if (shouldSwitch) {
      rows[i].parentNode.insertBefore(rows[i + 1], rows[i]); switching = true; switchcount++;
    } else {
      if (switchcount == 0 && dir == "asc") { dir = "desc"; switching = true; }
    }
  }
}
</script>
"@
$htmlHeader | Out-File $htmlOut -Encoding UTF8

# JSON init
$jsonData = @()

# === MAIN AUDIT LOOP ===
$users = Get-AllUsers
foreach ($u in $users) {
    $ouPath = Get-OUPath $u.DistinguishedName
    $groupNames = @()

    try {
        $groupDNs = $u.MemberOf
        $groupNames = $groupDNs | ForEach-Object { (Get-ADGroup $_).Name }
        $groupNames += $groupDNs | ForEach-Object { Get-NestedGroups $_ }
        $groupNames = $groupNames | Sort-Object -Unique
    } catch {}

    # Resolve GPOs + ACLs + other mappings
    $gpos    = Get-GPOsForUser $u.DistinguishedName
    $acls    = Get-ACLsForUser $u.SamAccountName
    $drives  = Get-MappedDrives $u.SamAccountName
    $exch    = Get-ExchangeBindings $u.SamAccountName

    # === WRITE TO CSV ===
    "$($u.SamAccountName),$($u.DisplayName),$ouPath,$($u.LastLogonDate),$($u.Enabled),""$($groupNames -join '; ')"" ,""$($gpos -join '; ')"" ,""$($acls -join '; ')"" ,""$($exch -join '; ')"" ,""$($drives -join '; ')""" |
            Out-File $csvOut -Append -Encoding UTF8

    # === WRITE TO MARKDOWN ===
    "| $($u.SamAccountName) | $($u.DisplayName) | $ouPath | $($u.LastLogonDate) | $($u.Enabled) | $($groupNames -join ', ') |" |
            Out-File $mdOut -Append -Encoding UTF8

    # === WRITE TO HTML ===
    "<tr><td>$($u.SamAccountName)</td><td>$($u.DisplayName)</td><td>$ouPath</td><td>$($u.LastLogonDate)</td><td>$($u.Enabled)</td><td>$($groupNames -join ', ')</td></tr>" |
            Out-File $htmlOut -Append -Encoding UTF8

    # === STRUCTURED JSON OUTPUT ===
    $jsonData += [PSCustomObject]@{
        Username   = $u.SamAccountName
        Display    = $u.DisplayName
        OU         = $ouPath
        LastLogon  = $u.LastLogonDate
        Enabled    = $u.Enabled
        Groups     = $groupNames
        GPOs       = $gpos
        ACLs       = $acls
        Drives     = $drives
        Exchange   = $exch
    }

    # === LOG ===
    Add-Content $log "`n=== [$($u.SamAccountName)] ==="
    Add-Content $log "OU: $ouPath"
    Add-Content $log "Groups:"
    $groupNames | ForEach-Object { Describe-Group $_ | Add-Content $log }
    Add-Content $log "`nGPOs:`n$($gpos -join "`n")"
    Add-Content $log "`nACLs:`n$($acls -join "`n")"
    Add-Content $log "`nExchange:`n$($exch -join "`n")"
    Add-Content $log "`nDrives:`n$($drives -join "`n")"
}

# === CLOSE HTML TABLE BODY AND DOCUMENT ===
"</tbody></table></body></html>" | Out-File $htmlOut -Append -Encoding UTF8

# === JSON EXPORT ===
$jsonData | ConvertTo-Json -Depth 5 | Out-File $jsonOut -Encoding UTF8

# === XLSX EXPORT BLOCK ===
$excelPath = "$OutDir\SharedAccounts-$ts.xlsx"

try {
    if (-not (Get-Module -ListAvailable -Name ImportExcel)) {
        Write-Host "[INFO] ImportExcel module not found — attempting install..." -ForegroundColor Yellow
        Install-Module -Name ImportExcel -Scope CurrentUser -Force
    }
    Import-Module ImportExcel -ErrorAction Stop

    $jsonData | Export-Excel -Path $excelPath -WorksheetName 'SharedAccounts' `
        -TableName 'AuditReport' -AutoSize -BoldTopRow -FreezeTopRow `
        -Title "Williams F1 Shared Account Audit – $ts"

    Write-Host "[XLSX] Export complete: $excelPath" -ForegroundColor Green
} catch {
    Write-Warning "[XLSX] Excel export failed: $_"
}

# === FINAL STATUS ===
Write-Host "`n[COMPLETE] AD AUDIT"
Write-Host " CSV     : $csvOut"
Write-Host " Markdown: $mdOut"
Write-Host " HTML    : $htmlOut"
Write-Host " JSON    : $jsonOut"
Write-Host " Log     : $log"

# === SNAPSHOT LOGIC ===

$snapDir     = "$PSScriptRoot\..\snapshots"
$snapFile    = "$snapDir\SharedAccounts-$($ts.Split('_')[0]).json"
$latestSnap  = Get-ChildItem -Path $snapDir -Filter "SharedAccounts-*.json" | Sort-Object LastWriteTime -Descending | Select-Object -First 1

# Ensure snapshot directory exists
if (!(Test-Path $snapDir)) {
    New-Item -Path $snapDir -ItemType Directory -Force | Out-Null
}

# Save current snapshot
try {
    $jsonData | ConvertTo-Json -Depth 5 | Set-Content -Path $snapFile -Encoding UTF8
    Write-Host "[SNAPSHOT] Saved baseline snapshot to: $snapFile" -ForegroundColor Green
} catch {
    Write-Warning "[SNAPSHOT] Failed to write snapshot: $_"
}

# === DRIFT DETECTION (COMPARE LAST SNAPSHOT TO THIS RUN) ===
if ($latestSnap) {
    try {
        $prev = Get-Content $latestSnap.FullName | ConvertFrom-Json
        $curr = $jsonData

        $diffUsers = Compare-Object $prev.Username $curr.Username -PassThru
        $diffText = @()

        if ($diffUsers.Count -gt 0) {
            $diffText += "`n=== Snapshot Drift Detected ==="
            $diffText += "Modified or Missing Users: $($diffUsers -join ', ')"
            Add-Content $log $diffText
            Write-Warning "[SNAPSHOT] Drift detected! Users changed since last snapshot."
        } else {
            Write-Host "[SNAPSHOT] No drift detected from previous snapshot." -ForegroundColor DarkGray
        }

    } catch {
        Write-Warning "[SNAPSHOT] Drift check failed: $_"
        Add-Content $log "`n[SNAPSHOT] Drift check error: $_"
    }
}

# ---------------------------------------------
# Export to PDF using HTML-to-PDF rendering
# ---------------------------------------------
# Requires wkhtmltopdf or equivalent installed
# Make sure path is valid — can adjust for your infra

$pdfPath = "$OutDir\SharedAccounts-$ts.pdf"
$htmlIn  = $htmlOut

# Change this to actual path for wkhtmltopdf
$wkhtmlPath = "C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"

if (Test-Path $wkhtmlPath) {
    & "$wkhtmlPath" --enable-local-file-access "$htmlIn" "$pdfPath"
    Write-Host "[PDF] Export complete: $pdfPath" -ForegroundColor Green
} else {
    Write-Warning "PDF Export failed — wkhtmltopdf not found at $wkhtmlPath"
}